### ISSUE TITLE
wrong test description

### ISSUE THREAD

**Issue by ihopeudie** [mikhama/core-js-101#16]
05-regex-tasks.js - getPasswordValidator

 - Valid passwords will only be alphanumeric characters.

```
AssertionError [ERR_ASSERTION]: Regex matches 'Pa__W0rd'
      + expected - actual

      -false
      +true
```

**Comment by mikhama** [comment]
Hi @ihopeudie,

What exact test description you mean wrong? In which file and line?
There in the file with the tasks are written all the rules:
https://github.com/mikhama/core-js-101/blob/acfcbfeaa9328e03cfa89de7c6b2204a562ee060/src/05-regex-tasks.js#L61-L83

**Comment by mikhama** [comment]
Do you mean that somwhere "underscore" word is missed?

**Comment by ihopeudie** [comment]
alphanumeric means numbers and digits

**Comment by mikhama** [comment]
Added missed "underscore" word:
https://github.com/mikhama/core-js-101/blob/d989a7d8960b4aff3c73f162b715bbcf95a04933/src/05-regex-tasks.js#L68
