### ISSUE TITLE
Wrong example in 03-arrays-tasks.js

### ISSUE THREAD

**Issue by wlukla** [mikhama/core-js-101#2]
function getHead in 03-arrays-tasks.js has wrong first example: 
[ 1, 3, 4, 5 ], 2  => [ 1, 2 ] 
should be: [ 1, 3, 4, 5 ], 2  => [ 1, 3 ]

**Comment by mikhama** [comment]
Thank you! I'll fix it.

**Comment by mikhama** [comment]
fixed
