### ISSUE TITLE
Wrong description of test 15 in 08-conditions-n-loops-tests.js

### ISSUE THREAD

**Issue by InvisibleSpectator** [mikhama/core-js-101#4]
![image](https://user-images.githubusercontent.com/33596224/70951352-9ec58600-207c-11ea-890e-cca97e5ee18a.png)

**Comment by mikhama** [comment]
@InvisibleSpectator could you please describe what is wrong here?

**Comment by InvisibleSpectator** [comment]
The "getCommonDirectoryPath" test should return a common path in the file system, but the description says it returns the n-ary string representation of number.
![image](https://user-images.githubusercontent.com/33596224/71256705-ff89e280-234a-11ea-87aa-55057d61b12b.png)

**Comment by mikhama** [comment]
Got it. Thank you!

**Comment by mikhama** [comment]
fixed
